# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViroKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViroKit
end

target 'ViroSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViroSample

end
